import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Grid, Link, Text, Spacer, Image } from "@nextui-org/react";

const codon: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Codon Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text
          h1
          size={60}
          css={{
            textGradient: "45deg, $blue500 -20%, $pink500 50%",
          }}
          weight="bold"
        >
          Codons
        </Text>
        <Grid.Container justify="center">
          <Grid xs={4}>
            <Text size={30}>
              <Spacer y={1} />A codon is a sequence of three nucleotides which
              together form a unit of genetic code in a DNA or RNA molecule. A
              codon table can be used to translate a genetic code into a
              sequence of amino acids. The standard genetic code is
              traditionally represented as an RNA codon table, because when
              proteins are made in a cell by ribosomes, it is messenger RNA
              (mRNA) that directs protein synthesis.
            </Text>
          </Grid>
          <Grid xs={4}>
            <ul>
              <Text
                small
                size={35}
                css={{
                  textGradient: "45deg, $green500, $blue500 90%",
                }}
                weight="bold"
              >
                Three features of codons:
              </Text>
              <li>
                <Text size={25}>
                  Each codon specifies an amino acid. The full set of
                  relationships between codons and amino acids is summarized as
                  a Condon Chart or Table.
                </Text>
              </li>
              <li>
                <Text size={25}>
                  One “Start” codon (AUG) marks the beginning of a protein. AUG
                  encodes the amino acid, called Methionine.
                </Text>
              </li>
              <li>
                <Text size={25}>
                  Three “Stop” codons mark the end of a protein and terminate
                  the translation.
                </Text>
              </li>
            </ul>
          </Grid>
        </Grid.Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/jordanhilado/AminoAcidDetection"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Jordan Hilado
        </a>
      </footer>
    </div>
  );
};

export default codon;
