import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Input, Button, Text, Grid, Link, Spacer } from "@nextui-org/react";
import { useState } from "react";

const Home: NextPage = () => {
  const [data, setData] = useState(null);
  const [translate, setTranslate] = useState(false);
  // get the sequence
  function getSeq(val: any) {
    setData(val.target.value);
    setTranslate(false);
  }
  // validate the input so that it is only a DNA or RNA sequence
  function validate(val: any) {
    if (val == null) {
      return false;
    }
    for (let i = 0; i < val.length; i++) {
      if (
        val[i] !== "A" &&
        val[i] !== "T" &&
        val[i] !== "C" &&
        val[i] !== "G" &&
        val[i] !== "U"
      ) {
        return false;
      }
    }
    return true;
  }
  // true = rna, false = dna
  function getType(seq: any) {
    if (seq.includes("U")) {
      return "RNA";
    } else {
      return "DNA";
    }
  }
  // write the complement of the dna sequence
  function getComplement(seq: any) {
    let complement = "";
    for (let i = 0; i < seq.length; i++) {
      if (seq[i] === "A") {
        complement += "U";
      } else if (seq[i] === "T") {
        complement += "A";
      } else if (seq[i] === "G") {
        complement += "C";
      } else if (seq[i] === "C") {
        complement += "G";
      }
    }
    return complement;
  }

  // use codon table to translate rna sequence to amino acid sequence
  function translateSeq(seq: any) {
    console.log("HERE1:", seq);
    let rna = seq.replace(/T/g, "U");
    let aminoAcid = "";
    let codon = "";
    let codonTable: { [key: string]: string } = {
      UUU: "Phe",
      UUC: "Phe",
      UUA: "Leu",
      UUG: "Leu",
      UCU: "Ser",
      UCC: "Ser",
      UCA: "Ser",
      UCG: "Ser",
      UAU: "Tyr",
      UAC: "Tyr",
      UGU: "Cys",
      UGC: "Cys",
      UAA: "STOP",
      UAG: "STOP",
      UGA: "STOP",
      UGG: "Trp",
      CUU: "Leu",
      CUC: "Leu",
      CUA: "Leu",
      CUG: "Leu",
      CCU: "Pro",
      CCC: "Pro",
      CCA: "Pro",
      CCG: "Pro",
      CAU: "His",
      CAC: "His",
      CAA: "Gln",
      CAG: "Gln",
      CGU: "Arg",
      CGC: "Arg",
      CGA: "Arg",
      CGG: "Arg",
      AUU: "Ile",
      AUC: "Ile",
      AUA: "Ile",
      AUG: "Met",
      ACU: "Thr",
      ACC: "Thr",
      ACA: "Thr",
      ACG: "Thr",
      AAU: "Asn",
      AAC: "Asn",
      AAA: "Lys",
      AAG: "Lys",
      AGU: "Ser",
      AGC: "Ser",
      AGA: "Arg",
      AGG: "Arg",
      GUU: "Val",
      GUC: "Val",
      GUA: "Val",
      GUG: "Val",
      GCU: "Ala",
      GCC: "Ala",
      GCA: "Ala",
      GCG: "Ala",
      GAU: "Asp",
      GAC: "Asp",
      GAA: "Glu",
      GAG: "Glu",
      GGU: "Gly",
      GGC: "Gly",
      GGA: "Gly",
      GGG: "Gly",
    };
    let ptr = 0;
    for (let i = 0; i < rna.length; i += 1) {
      codon = rna.substring(i, i + 3);
      if (codon === "AUG") {
        ptr = i;
      }
    }
    while (ptr < rna.length) {
      codon = rna.substring(ptr, ptr + 3);
      if (codonTable[codon] === "STOP") {
        break;
      }
      aminoAcid += codonTable[codon];
      ptr += 3;
    }
    return aminoAcid;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Amino Acid Detection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text
          h1
          size={60}
          css={{
            textGradient: "45deg, $blue500, $pink500 50%",
          }}
          weight="bold"
        >
          Amino Acid Detection
        </Text>
        <p className={styles.description}>Input the DNA/RNA sequence.</p>
        <Input
          width="600px"
          labelPlaceholder="Sequence"
          size="xl"
          onChange={getSeq}
        />
        {translate ? (
          <div>
            {validate(data) ? (
              <div>
                <Spacer y={2.5} />
                <div style={{ textAlign: "center" }}>
                  <Text h6 size={30} weight="light">
                    1. The sequence
                  </Text>
                  <Text
                    h1
                    size={30}
                    css={{
                      textGradient: "45deg, $pink500 20%, $blue500",
                    }}
                    weight="bold"
                  >
                    {data}
                  </Text>
                  <Text h6 size={30} weight="light">
                    is a {getType(data)} sequence.
                  </Text>
                </div>
                <Spacer x={1} />
                {getType(data) === "DNA" ? (
                  <div style={{ textAlign: "center" }}>
                    <Text h6 size={30} weight="light">
                      2. Convert to RNA:
                    </Text>
                    <Text
                      h1
                      size={30}
                      css={{
                        textGradient: "45deg, $pink500 50%, $blue500",
                      }}
                      weight="bold"
                    >
                      {getComplement(data)}
                    </Text>
                    <Spacer y={1} />
                    <Text h6 size={30} weight="light">
                      3. Translate with codon table:
                    </Text>
                    <Text
                      h1
                      size={40}
                      css={{
                        textGradient: "45deg, $blue500, $pink500 50%",
                      }}
                      weight="bold"
                    >
                      {translateSeq(getComplement(data))}
                    </Text>
                  </div>
                ) : (
                  <div style={{ textAlign: "center" }}>
                    <Text h6 size={30} weight="light">
                      2. Translate with codon table:
                    </Text>
                    <Text
                      h1
                      size={40}
                      css={{
                        textGradient: "45deg, $blue500, $pink500 50%",
                      }}
                      weight="bold"
                    >
                      {translateSeq(data)}
                    </Text>
                  </div>
                )}
              </div>
            ) : (
              <div>
                <h1>INPUT A VALID SEQUENCE</h1>
              </div>
            )}
          </div>
        ) : null}
        <Spacer y={1} />
        <Button
          onClick={() => setTranslate(true)}
          color="gradient"
          size="xl"
          auto
          ghost
        >
          Translate
        </Button>
        <Spacer y={2.5} />
        <h2>Learn more:</h2>
        <div style={{ display: "flex", columnGap: 20 }}>
          <Link href="/dna">
            <Button size="xl" shadow color="gradient" auto>
              DNA
            </Button>
          </Link>
          <Link href="/rna">
            <Button size="xl" shadow color="gradient" auto>
              RNA
            </Button>
          </Link>
          <Link href="/aminoacids">
            <Button size="xl" shadow color="gradient" auto>
              Amino Acids
            </Button>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/jordanhilado/AminoAcidDetection"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Jordan Hilado
        </a>
      </footer>
    </div>
  );
};

export default Home;
