import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Input, Button, Grid, Link, Spacer } from "@nextui-org/react";
import { useState } from "react";

const Home: NextPage = () => {
  const [data, setData] = useState(null);
  const [translate, setTranslate] = useState(false);
  function getSeq(val) {
    setData(val.target.value);
    setTranslate(false);
  }
  // true = rna, false = dna
  function getType(seq) {
    if (seq.includes("U")) {
      return "RNA";
    } else {
      return "DNA";
    }
  }
  // write the complement of the dna sequence
  function getComplement(seq) {
    let complement = "";
    for (let i = 0; i < seq.length; i++) {
      if (seq[i] === "A") {
        complement += "U";
      } else if (seq[i] === "T") {
        complement += "A";
      } else if (seq[i] === "G") {
        complement += "C";
      } else if (seq[i] === "C") {
        complement += "G";
      }
    }
    return complement;
  }

  // use codon table to translate rna sequence to amino acid sequence
  function translateSeq(seq) {
    console.log("HERE1:", seq);
    let rna = seq.replace(/T/g, "U");
    let aminoAcid = "";
    let codon = "";
    let codonTable: { [key: string]: string } = {
      UUU: "Phe",
      UUC: "Phe",
      UUA: "Leu",
      UUG: "Leu",
      UCU: "Ser",
      UCC: "Ser",
      UCA: "Ser",
      UCG: "Ser",
      UAU: "Tyr",
      UAC: "Tyr",
      UGU: "Cys",
      UGC: "Cys",
      UAA: "STOP",
      UAG: "STOP",
      UGA: "STOP",
      UGG: "Trp",
      CUU: "Leu",
      CUC: "Leu",
      CUA: "Leu",
      CUG: "Leu",
      CCU: "Pro",
      CCC: "Pro",
      CCA: "Pro",
      CCG: "Pro",
      CAU: "His",
      CAC: "His",
      CAA: "Gln",
      CAG: "Gln",
      CGU: "Arg",
      CGC: "Arg",
      CGA: "Arg",
      CGG: "Arg",
      AUU: "Ile",
      AUC: "Ile",
      AUA: "Ile",
      AUG: "Met",
      ACU: "Thr",
      ACC: "Thr",
      ACA: "Thr",
      ACG: "Thr",
      AAU: "Asn",
      AAC: "Asn",
      AAA: "Lys",
      AAG: "Lys",
      AGU: "Ser",
      AGC: "Ser",
      AGA: "Arg",
      AGG: "Arg",
      GUU: "Val",
      GUC: "Val",
      GUA: "Val",
      GUG: "Val",
      GCU: "Ala",
      GCC: "Ala",
      GCA: "Ala",
      GCG: "Ala",
      GAU: "Asp",
      GAC: "Asp",
      GAA: "Glu",
      GAG: "Glu",
      GGU: "Gly",
      GGC: "Gly",
      GGA: "Gly",
      GGG: "Gly",
    };
    let ptr = 0;
    for (let i = 0; i < rna.length; i += 1) {
      codon = rna.substring(i, i + 3);
      if (codon === "AUG") {
        ptr = i;
      }
    }
    while (ptr < rna.length) {
      codon = rna.substring(ptr, ptr + 3);
      if (codonTable[codon] === "STOP") {
        break;
      }
      aminoAcid += codonTable[codon];
      ptr += 3;
    }
    return aminoAcid;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Amino Acid Detection</h1>
        <p className={styles.description}>Input the DNA/RNA sequence.</p>
        <Input
          width="600px"
          placeholder="Sequence"
          size="xl"
          onChange={getSeq}
        />
        {translate ? (
          <div>
            <Spacer y={2.5} />
            Your sequence {data} is {getType(data)}
            <Spacer x={1} />
            {getType(data) === "DNA" ? (
              <div>
                WE NEED TO CONVERT TO RNA. Converted sequence is{" "}
                {getComplement(data)}
                We now can use the codon table to translate it:
                {translateSeq(getComplement(data))}
              </div>
            ) : (
              <div>
                since it is already in RNA, we then translate with the table
                Translated sequence: {translateSeq(data)}
              </div>
            )}
          </div>
        ) : null}
        <Spacer y={2.5} />
        <Button
          onClick={() => setTranslate(true)}
          color="secondary"
          size="xl"
          auto
          ghost
        >
          Translate
        </Button>
        <Spacer y={2.5} />
        <h2>Learn more:</h2>
        <Grid>
          <Link href="/dna">
            <Button size="xl" shadow color="secondary" auto>
              DNA
            </Button>
          </Link>
          <Link href="/rna">
            <Button size="xl" shadow color="secondary" auto>
              RNA
            </Button>
          </Link>
          <Link href="/aminoacids">
            <Button size="xl" shadow color="secondary" auto>
              Amino Acids
            </Button>
          </Link>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/jordanhilado/AminoAcidDetection"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Jordan Hilado
        </a>
      </footer>
    </div>
  );
};

export default Home;
